### ISSUE TITLE
Doesn't work on iPhone 4S (iOS 7.1.2)

### ISSUE THREAD

**Issue by rpellerin** [TheSmiths-Widgets/ts.camera#1]
``` javascript
cameraView = iosCameraView.createView({
            height: <something in px>,
            width: <something in px>,
            detectCodes:true,
            backgroundColor: '#fff',
            frontQuality: iosCameraView.QUALITY_HIGH,
            backQuality: iosCameraView.QUALITY_HD,
            camera: 'front'
})
```

It says: `Can not use camera quality 'AVCaptureSessionPresetHigh'. Defaulting to High.` and then crashes.

Any clue?
Thanks

**Comment by bduyng** [comment]
the error from this
[https://github.com/mikefogg/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L332](https://github.com/mikefogg/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L332) :)

**Comment by PierreGUI** [comment]
Do you think you can fix it ? :)

2016-01-11 16:24 GMT+01:00 Duy Bao Nguyen notifications@github.com:

> the error from this
> 
> https://github.com/mikefogg/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L332
> :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheSmiths-Widgets/ts.camera/issues/1#issuecomment-170586156
> .

## 

Pierre VAN DE VELDE
CTO at The Smiths - www.wearesmiths.com

**Comment by bduyng** [comment]
I am thinking how I can get ios 7.1.2 first :). I will have a look and see if we can download an old version of simulator in xcode

**Comment by rpellerin** [comment]
Yes but I get the same message on an iPhone 5 S and still, it works

**Comment by bduyng** [comment]
Do we need to support for 7.1.2?. the earliest version I can download is 8.1

**Comment by bduyng** [comment]
I found this. can you guys double check we are using the lastest version of the module
[https://github.com/mikefogg/SquareCamera/issues/28](https://github.com/mikefogg/SquareCamera/issues/28)

**Comment by rpellerin** [comment]
Version 0.6 works on iOS 7.1.2 indeed, thanks :)

**Comment by bduyng** [comment]
you are welcome :)
